# Generated by Django 5.2.5 on 2025-09-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book'), ('can_view_book', 'Can view book')], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
