# Generated by Django 5.2.5 on 2025-08-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='bookshelf_book',
        ),
    ]
